### ISSUE TITLE
Add a field of view (fov) property

### ISSUE THREAD

**Issue by PanierAvide** [stac-extensions/perspective-imagery#5]
Hello,

As we're making use of STAC and its extension in [a project to allow hosting of street imagery](https://gitlab.com/PanierAvide/geovisio), we would find interesting to have a property allowing to describe the camera [field of view](https://en.wikipedia.org/wiki/Field_of_view). This would allow us to make a standardized distinction between 360° pictures and classic pictures (useful for a web viewer to have a proper rendering).

If this proposal makes sense to you, I can offer a PR to add this in the extension.

Best regards.

**Comment by AsgerPetersen** [comment]
Hi @PanierAvide 

Thank you for raising this issue! 

"Field of view" seems like a good candidate for inclusion in this extension. I guess there are cases where an estimated field of view is the best available information about the camera. Also - together with the `perspective_centre` and `view:azimuth` the field of view would give a pretty good idea of the scene. So your PR is very welcome.

I am a little curious about how well 360° would fit with this extension. Could you share how you plan to describe your data?

Best regards
Asger

**Comment by PanierAvide** [comment]
Hi, thanks for your feedback. I will work on the pull request soon.

We already have a working API to offer 360° pictures metadata, here's [an example collection](https://geovisio.fr/api/collections/35986201-efc6-43e4-b3e7-fff3d03d745c) and here [an example of a single picture](https://geovisio.fr/api/collections/35986201-efc6-43e4-b3e7-fff3d03d745c/items/a240a0a5-3aac-4ca9-b3a4-0aa877d87713). As I'm quite new to the world of STAC schemes, you may have some suggestions about improvements on it was implemented.

Best regards.

**Comment by heidivanparys** [comment]
@PanierAvide The STAC community seems to be most active on gitter, I would recommend also asking for feedback in https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby.

**Comment by AsgerPetersen** [comment]
@PanierAvide I am sorry. I have been busy lately. The links seem to be broken now.

**Comment by PanierAvide** [comment]
Sorry for that, here is a more stable URL for collections : https://geovisio.fr/api/collections/ And for individual pictures : https://geovisio.fr/api/search

**Comment by AsgerPetersen** [comment]
Thank you. The `field_of_view` is a very welcome contribution to this spec.

I am no expert in 360 degree images, so I dont know if it is defined as perspective imagery. But it seems to make sense in your use case.
