### ISSUE TITLE
Validation issue with schema.json stac_extension's URL

### ISSUE THREAD

**Issue by PanierAvide** [stac-extensions/perspective-imagery#9]
Hello,

I'm trying to make the [API I'm working on](https://gitlab.com/geovisio/geovisio) tested against STAC specs using [STAC API Validator](https://github.com/stac-utils/stac-api-validator).

As I use this extension for describing geolocated pictures, the URL to extension is set in my items' `stac_extensions` field. The only URL I found to use is `https://raw.githubusercontent.com/stac-extensions/perspective-imagery/main/json-schema/schema.json`, as the schema isn't available on `https://stac-extensions.github.io/perspective-imagery/v1.0.0/schema.json`. But, in the JSON schema, the STAC extension URL [should match the `stac-extensions.github.io` URL](https://github.com/stac-extensions/perspective-imagery/blob/main/json-schema/schema.json#L164). This causes issues against the validator :

- If I use working URL, validator gives error because schema is not fully validated
- If I use the `stac-extensions.github.io` URL, validator can't find the extension's schema, then fails

Would it be possible to find a solution for this ? Either removing the `stac_extension` requirement in `schema.json`, or publish the existing version on stac-extensions.github.io.

Best regards.

**Comment by m-mohr** [comment]
The extension needs to be released for this. @AsgerPetersen do you want to do this? Otherwise, I could also click the buttons...

**Comment by AsgerPetersen** [comment]
@m-mohr I would appreciate it very much if you could help us out here. I am quite busy at the moment.

**Comment by m-mohr** [comment]
Done, the schema identifier https://stac-extensions.github.io/perspective-imagery/v1.0.0/schema.json is now available.

**Comment by AsgerPetersen** [comment]
Thank you very much @m-mohr !

**Comment by PanierAvide** [comment]
Thanks for solving the issue, that will be very helpful :clap:
